{
 "title": "Database Exporter",
 "time": { "from": "2025-11-06T12:46:32.835Z", "to": "2025-11-06T12:47:26.009Z" },
 "templating": {
  "list": [
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Tuples Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_fetched{datname=\"ecommerce_olist\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rows Fetched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"ecommerce_olist\"}[3m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffers Read",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"ecommerce_olist\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buffers Hit",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"ecommerce_olist\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tuples Inserted",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{datname=\"ecommerce_olist\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (rollbacks/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"ecommerce_olist\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS (commits/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"ecommerce_olist\"}[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Size (GB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"ecommerce_olist\"} / 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime (seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "Connections" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"ecommerce_olist\", state=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}